Introduce "test-dev" target of Makefile
France-ioi/AlgoreaBackend pull request #1110
Opened 2024-07-14 22:26 UTC by zenovich

As a subtask of #1105 , here we introduce a new Makefile target named 'test-dev' which runs test without code coverage collecting and without verbose output in order to enable per-package caching.

2024-07-15 14:53 UTC, smadbe requested changes
Some explanation  should be added somehow (in the readme?), otherwise it is not really possible to guess what "test-dev" is for.

2024-07-15 19:16 UTC, zenovich commented
How it looks like on the second run when all the tests pass:
```
% time make test-dev
env GO111MODULE=auto go test -gcflags=all=-l ./app/... -p 1 -parallel 1 
ok  	github.com/France-ioi/AlgoreaBackend/app	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/answers	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/auth	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/contests	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/currentuser	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/groups	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/items	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/threads	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/api/users	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/appenv	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/auth	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/database	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/database/configdb	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/database/mysqldb	(cached)
?   	github.com/France-ioi/AlgoreaBackend/app/doc	[no test files]
ok  	github.com/France-ioi/AlgoreaBackend/app/domain	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/encrypt	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/formdata	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/logging	0.702s
?   	github.com/France-ioi/AlgoreaBackend/app/loggingtest	[no test files]
ok  	github.com/France-ioi/AlgoreaBackend/app/loginmodule	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/payloads	(cached)
?   	github.com/France-ioi/AlgoreaBackend/app/payloadstest	[no test files]
ok  	github.com/France-ioi/AlgoreaBackend/app/rand	(cached)
ok  	github.com/France-ioi/AlgoreaBackend/app/service	(cached)
?   	github.com/France-ioi/AlgoreaBackend/app/servicetest	[no test files]
?   	github.com/France-ioi/AlgoreaBackend/app/structures	[no test files]
ok  	github.com/France-ioi/AlgoreaBackend/app/token	(cached)
?   	github.com/France-ioi/AlgoreaBackend/app/tokentest	[no test files]
ok  	github.com/France-ioi/AlgoreaBackend/app/utils	(cached)
?   	github.com/France-ioi/AlgoreaBackend/app/version	[no test files]
make test-dev  4.01s user 1.56s system 107% cpu 5.177 total
```

2024-07-15 20:08 UTC, zenovich commented
> Some explanation should be added somehow (in the readme?), otherwise it is not really possible to guess what "test-dev" is for.

Added it to README.md

2024-07-16 07:41 UTC, smadbe approved these changes

2024-07-16 07:47 UTC, smadbe commented
FYI @GeoffreyHuck

2024-07-16 07:49 UTC, merged