Do not display ContestParticipants group anywhere, correct group type enums in swagger docs
France-ioi/AlgoreaBackend pull request #821
Opened 2021-12-16 09:55 UTC by zenovich

Fixes #795

2021-12-20 10:13 UTC, smadbe approved these changes

2021-12-20 10:16 UTC, smadbe requested changes
I think you haven't handled the remark https://github.com/France-ioi/AlgoreaBackend/issues/795#issuecomment-943131446 of the issue. Do you plan to do it in a separate PR?

2022-01-09 23:28 UTC, zenovich commented
> I think you haven't handled the remark [#795 (comment)](https://github.com/France-ioi/AlgoreaBackend/issues/795#issuecomment-943131446) of the issue. Do you plan to do it in a separate PR?

invitationsView output docs have been updated

2022-01-09 23:33 UTC, zenovich commented
> I think you haven't handled the remark [#795 (comment)](https://github.com/France-ioi/AlgoreaBackend/issues/795#issuecomment-943131446) of the issue. Do you plan to do it in a separate PR?

Fixed swagger docs of groupsPossibleSubgroupsSearch. So it seems everything is done.

2022-01-11 09:29 UTC, smadbe approved these changes

2022-01-11 14:01 UTC, merged