Service get best answer
France-ioi/AlgoreaBackend pull request #880
Opened 2023-01-23 16:34 UTC by GeoffreyHuck

Fixes 874

2023-01-23 16:47 UTC, GeoffreyHuck commented
Fixes #874

2023-01-24 11:10 UTC, smadbe requested changes
Looks good overall 👍 

For each remark, answer "fixed" when done (or explain if you don't fix) so that I can re-review and I will mark them "resolved" myself on GH.

2023-01-24 15:14 UTC, GeoffreyHuck commented on app/api/answers/get_best.feature
> +    | 107 | 11        | 11             | 1          | 210     | Submission | Current | print(7) | 2017-05-29 08:38:38 |
fixed for all tests

2023-01-24 16:03 UTC, GeoffreyHuck commented on app/api/answers/get_best.feature
> +    | id  | author_id | participant_id | attempt_id | item_id | type       | state   | answer   | created_at          |
fixed

2023-01-24 16:11 UTC, GeoffreyHuck commented on app/api/answers/get_best.go
> +	if watchedGroupID != 0 && watchedGroupIDSet {
fixed, it was useless. Wouldn't it be even better to rename watchedGroupIDSet into "ok" to follow the "comma ok idiom" ?

2023-01-24 16:18 UTC, GeoffreyHuck commented on app/api/answers/get_best.go
> +			Joins("JOIN `groups` ON groups.id = groups_ancestors_active.child_group_id").
fixed, it came from an other service. I deleted it there too.

2023-01-24 16:43 UTC, GeoffreyHuck commented on app/api/answers/get_best.go
> +			Where("author_id = ?", user.GroupID)
fixed. I also added a test that covers the case.

I removed `.Visible(user)` that makes more checks than required and replaced it with `WherePermissionIsAtLeast("view", "content")` instead.

2023-01-24 16:44 UTC, GeoffreyHuck commented on app/api/answers/get_best.feature
> +      "id": "103",
fixed

2023-01-24 16:46 UTC, smadbe commented on app/api/answers/get_best.go
> +	if watchedGroupID != 0 && watchedGroupIDSet {
Yes, don't know why it has not been done initially.

2023-01-25 09:40 UTC, smadbe approved these changes
great 👍

2023-01-30 08:07 UTC, merged