Migrate prod database
France-ioi/AlgoreaBackend pull request #992
Opened 2023-08-16 09:05 UTC by GeoffreyHuck

- Cherry-picked migrations in https://github.com/France-ioi/AlgoreaBackend/pull/917
- Deduplicate `groups`.`sPassword`

2023-09-06 13:31 UTC, smadbe requested changes
Could you check what fails in the test? It seems to be a legitimate error, so probably there is something to fix (otherwise, the next PR containing migrations will fail as well I think)

2023-09-07 06:08 UTC, GeoffreyHuck commented on db/migrations/1900000000__preprod-changes.sql
> +ALTER TABLE `groups_login_prefixes` DROP COLUMN `idUserCreator`;
This is the line that makes the migration fail

2023-09-07 06:10 UTC, GeoffreyHuck commented
I annoted the line with the migration problem here: https://github.com/France-ioi/AlgoreaBackend/pull/992/files

It looks like the database used doesn't have the same schema as the one used to write the migrations.

2023-09-07 07:13 UTC, smadbe commented
Ok, but at the end we have to do something to prevent this error to raise each time we write a migration from now. Either fix the db seed and fix the migration file.

2023-09-11 13:19 UTC, smadbe requested changes
So this is not waiting for my review anymore I think.

2026-01-23 09:01 UTC, closed without merging